name: Test Export Smartcat Data

on:
  workflow_dispatch:

jobs:
  export_data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Smartcat Translation Import/Export
        uses: ./
        with:
          actionType: 'export'
          accountID: 'c5a662fe-66ae-4793-ae1a-9e386d03a7a0'
          apiToken: '2_XQQLY543auuTp2Ss8ZOPs1L7k'
          projectID: '85381a5c-a1ce-4301-a4e0-548a8869ac64'
          apiServer: 'https://smartcat.com'
          languages: 'en'
          pathSeparator: '/'
          format: 'structured-json'
          outputFilePathTemplate: '{LANGUAGE}.json'
          outputPath: './languages'
          githubToken: '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'
